const Map<String,String> tr = {
  "My Profile" : "Profilim",
  "Last Calls" : "Son Aramalar",
  "Last Deals" : "Son Anlaşmalar",
  "Offers" : "Tekliflerim",
  "Chat" : "Mesajlar",
  "Help" : "Yardım",
  "Cancel" : "İptal",
  "Send" : "Gönder",
  "kullanım koşulları" : "Kullanıcı Sözleşmesi",
  "Gazilik" : "Gizlilik Sözleşmesi",
  "Price" : "Fiyat",
  "detail" : "Teklif Detayı",
  "Day" : "Gün",
  "Time" : "Saat",
  "Note" : "Not",
  "Puanla" : "Puan Ver",
  "Report" : "Şikayet Et",
  "fav" : "Favorilere Ekle",
  "un fav" : "Favorilerden Çıkar",
  "Engelle" : "Engelle",
  "Engeli Kaldır" : "Engeli Kaldır",
  "Blocked Users" : "Engellenen Kullanıcılar",
  "Blocked" : "Engellenenler",
  "Favorite" : "Favoriler",
  "Not Answered" : "Cevapsız Çağrı",
  "Answered" : "Yanıtlandı",
  "Female" : "Kadın",
  "Male" : "Erkek",
  "undefined" : "Tanımsız",
  "Update" : "Güncelle",
  "Log Out" : "Çıkış Yap",
  "Delete My Account" : "Hesabımı Sil",
  "Teklif" : "Teklif Ver",
  "Warning" : "Dikkat",
  "No" : "Hayır",
  "Yes" : "Evet",
  "Set your custom comment hint" : "Kullanıcıya yorum yaz...",
  "Submit" : "Gönder",
  "Bu kullanıcıyı gerçekten fav istiyor musunuz ?" : "Bu kullanıcıyı favorilerine eklemek istiyor musun ?",
  "Kullanıcı fav kaldırmak istiyor musunuz ?" : "Bu kullanıcıyı favorilerinden kaldırmak istiyor musun ?",
  "Bu kullanıcıyı gerçekten engellemek istiyor musunuz ?" : "Bu kullanıcıyı gerçekten engellemek istiyor musunuz ?",
  "Kullanıcı engelini kaldırmak istiyor musunuz ?" : "Bu kullanıcının engelini kaldırmak istiyor musun  ?",
  "hint" : "Lütfen detay verin",
  "Un Block" : "Engeli Kaldır",
};



