name: zebra
description: zebra
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ## Firebase
  firebase_core: ^3.1.0
  firebase_analytics: ^11.1.0
  firebase_crashlytics: ^4.0.2
  firebase_remote_config: ^5.0.2
  firebase_messaging: ^15.0.1

  cupertino_icons: ^1.0.2
  dio:
  hive:
  get: ^4.6.6
  flutter_dropdown_alert:
  path_provider:
  provider:
  device_info_plus: ^10.1.0
  flutter_spinkit:
  location:
  lottie:
  custom_pop_up_menu:
  statusbarmanager:
  advanced_icon:
  url_launcher: ^6.2.6
  flutter_launch:
  custom_timer: ^0.2.3
  whatsapp_unilink:
  google_maps_flutter:
  avatar_glow:
  flutter_animarker:
  geolocator: 9.0.1
  webview_flutter: 3.0.4
  quickalert:
  flutter_ringtone_player:
  toggle_switch:
  flutter_expanded_tile:
  flutter_webrtc: ^0.11.1
  uuid:
  flutter_callkit_incoming: 1.0.3+3
  #advanced_audio_manager:
  proximity_sensor:
  flutter_datetime_picker:
    git:
      url: https://github.com/HasanAlqaisi/flutter_datetime_picker.git
  circular_widgets:
  gallery_saver:
  open_filex:
  intl: ^0.18.1
  rating_dialog:
  # flutter_incall_manager:
  #   git: https://github.com/manozzreddy/flutter-incall-manager.git
  socket_io_client: 2.0.1
  flutter_launcher_icons:
  geocoding:
  widget_circular_animator:
  flutter_chat_ui:
  stacked:
  jiffy: ^6.2.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  flutter_dotenv: ^5.1.0
  logger: ^2.3.0
  get_storage: ^2.1.1
  package_info_plus: ^8.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  phone_form_field: ^9.2.5
  flutter_native_splash: ^2.4.0



flutter_icons:
  android: true
  ios: true
  image_path: "assets/app/appLogo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  generate: true
  uses-material-design: true


  assets:
    - env/
    - assets/
    - assets/images/
    - assets/flags/
    - assets/app/
    - assets/icons/
    - assets/font/
    - assets/categoryIcons/

  fonts:
    - family: Century
      fonts:
        - asset: assets/font/Century Gothic.ttf